### ISSUE TITLE
Add box drawing character constants

### ISSUE THREAD

**Issue by DariuszDepta** [DecisionToolkit/dte#8]
Add constants for the rest of the box drawing characters like this:

```rust
/// `│` `U+2502` Box drawings light vertical.
/// ```
/// # use dtee::*;
/// assert_eq!('│', LIGHT_VERTICAL);
/// assert_eq!('\u{2502}', LIGHT_VERTICAL);
/// ```
pub const LIGHT_VERTICAL: char = '\u{2502}';
```
Replace the box drawing characters used everywhere in code with the constants.

Example in the source code:
https://github.com/DecisionToolkit/dte/blob/cbd1fd408bf8608cce9a96f17bdb8870bd6bfab8/engine/src/model/characters.rs#L22-L30

**Comment by miroim** [comment]
If no one is working on this, I would like to give it a try.
